name: Build and run Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 3la-ir-example
    - name: Run the Docker image
      run: docker run 3la-ir-example > printed-ir.txt 2>&1
    - uses: actions/upload-artifact@v2
      with:
        name: printed-ir.txt
        path: printed-ir.txt

